include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    no_default_cases: false
    public_member_api_docs: false
    prefer_constructors_over_static_methods: false
    require_trailing_commas: false
