include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    prefer_int_literals: false
    prefer_constructors_over_static_methods: false
